### ISSUE TITLE
404 errors in GitHub section

### ISSUE THREAD

**Issue by JuanPabloDiaz** [oktay/oktaycolakoglu-2022#45]
In your GitHub section:  **Last activities from Github** there are a couple of 404 errors

- [movielister](https://github.com/oktay/movielister)
- [cakrazemlak](https://github.com/oktay/cakrazemlak)
- [hackintosh-msi-ge60](https://github.com/oktay/hackintosh-msi-ge60)
- [cakrazemlak-cms](https://github.com/oktay/cakrazemlak-cms)

This is probably because you make the repos private, or they are gone.

Other suggestions:
- I also recommend making the box clickable and not only the title. (it was hard to me to figure out how to open them).
- You have a typo in "Last developed projetcs" section. it should be **`projects`**

**Comment by oktay** [comment]
Hi, thank you for identifying the errors and creating this issue. I have resolved the problems mentioned in commit 10e4d5d. Since there hasn't been a new build for a long time, as you mentioned, private or deleted repositories were still visible. It might be necessary to remove those parts from the SSG.

Thanks again!
